#include <Windows.h>

#include <chrono>
#include <iostream>
#include <vector>

#include "solution.h"
#include "utility.h"
using chrono_clock = std::chrono::high_resolution_clock;
#define TIME_DIFF(x, y) \
    std::chrono::duration_cast<std::chrono::microseconds>((y) - (x)).count()
int main()
{
    /*
    The input might be generated by reading data from files.
    */
    std::vector<std::vector<std::vector<int>>> dataset1A = {
        {{1, 0, 0}, {0, 1, 0}, {0, 0, 1}}};
    std::vector<std::vector<int>> dataset1x = {{1, 0, 0}};

    /*
      Generate M x N matrix
    */
    std::vector<std::vector<std::vector<float>>> dataset1B;
    std::vector<std::vector<float>> dataset1bx;
    dataset1B.push_back(GenerateMatrixMN<float>(100, 1000));
    dataset1bx.push_back(GenerateMatrixN1<float>(1000));

    long long timeDiffSum1 = 0;
    const int L1 = dataset1A.size();
    /*
base example
*/
    // for (int i = 0; i < L1; i++)
    // {
    //     auto s = smartmore::Solution();
    //     auto start = chrono_clock::now();
    //     float result = s.clacModule<float>(dataset1B[i], dataset1bx[i]);
    //     std::cout << "Base result  = " << result << std::endl;
    //     auto end = chrono_clock::now();
    //     timeDiffSum1 += TIME_DIFF(start, end);
    // }
    // std::cout << "Base time  = " << timeDiffSum1 << std::endl;
    
    timeDiffSum1 = 0;
    /*
    round 1 example
    */
    for (int i = 0; i < L1; i++)
    {
        auto s = smartmore::Solution();
        auto start = chrono_clock::now();
        float result = s.clacModule_thread<int>(dataset1A[i], dataset1x[i]);
        std::cout << "Round 1 result  = " << result << std::endl;
        auto end = chrono_clock::now();
        timeDiffSum1 += TIME_DIFF(start, end);
    }
    std::cout << "Round 1 time = " << timeDiffSum1 << std::endl;

    return 0;
}